[package]
name = "apur_model"
version = "0.1.0"
authors = ["Strexicious <strexicious@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apur_renderer = { path = "../apur_renderer" }
wgpu = "0.5.0"
