[package]
name = "apur_renderer"
version = "0.1.0"
authors = ["Strexicious <strexicious@gmail.com>"]
edition = "2018"

[dependencies]
wgpu = "0.5.0"
winit = "0.21.0"
image = "0.22.4"
glam = "0.8.6"
zerocopy = "0.3.0"
log = "0.4"
